### ISSUE TITLE
weighted KNN, which weights?

### ISSUE THREAD

**Issue by reidmcy** [UC-MACSS/persp-model#296]
For the assignment is simply says is simply says '_Calculate the test MSE for weighted KNN models_', it does not say what type of weights to use. How should we derive the weights?

**Comment by bensoltoff** [comment]
Choose your own adventure. You can go with the default settings for whatever package you are using (R or Python), or do some cross-validation analysis to determine the optimal parameters. If you use `kknn::kknn()` (as I demonstrate in the notes), the default uses Euclidean distance to calculate distance between observations and the ["optimal" kernel function](https://arxiv.org/pdf/1101.5783.pdf) to calculate the weighted average. You can use other kernels if you want, see the help file for `kknn()` to see which kernels are available or the help file for the Python implementation you use.
